### ISSUE TITLE
JS Error on ebay-combobox

### ISSUE THREAD

**Issue by cc-ebay** [eBay/ebayui-core#1771]
# Bug Report

## Description
If we press `Esc` or `Return` in the input there is a JS error:
```
component.js:81 Uncaught TypeError: Cannot read properties of null (reading 'expanded')
    at component.js:81:1
    at handleKeydown (index.js:10:1)
    at Module.handleEnterKeydown (index.js:24:1)
    at EbayCombobox.handleComboboxKeyDown (component.js:80:1)
    at delegateEvent (event-delegation.js:65:1)
    at addEventListener.listeners.<computed> (event-delegation.js:117:1)
```

**Comment by cc-ebay** [comment]
`this.expander` may be `null` (closed) in `this.expander.expanded`
