### ISSUE TITLE
Carousel: "Error: No widget found" when w-id on child component

### ISSUE THREAD

**Issue by sraone** [eBay/ebayui-core#419]
# Bug Report

## Description
Facing an error `Error: No widget found` when trying to add another component with `w-id` within `ebay-carousel-item`. But, same is working fine if I take out the `w-id` attribute.

```marko
<ebay-carousel
        w-id="test-carousel"
    >
        <ebay-carousel-item>
            <ebay-notice
                w-id="error"
                a11y-heading-text="Priority"
                a11y-heading-tag="h3" 
                status="priority" 
                type="page">
                <p>Couldn't load all the items, please try again later.</p>
            </ebay-notice>
        </ebay-carousel-item>
    </ebay-carousel>
```

```
Error: No widget found
    at getCurrentWidget (/Users/skalluri1/Workspace/sraone/marko-widgets-lasso/node_modules/marko-widgets/taglib/helpers/getCurrentWidget.js:26:15)
    at render (/Users/skalluri1/Workspace/sraone/marko-widgets-lasso/src/components/number-spinner/template.marko.js:28:18)
    at Object.render (/Users/skalluri1/Workspace/sraone/marko-widgets-lasso/node_modules/marko/runtime/marko-runtime.js:192:9)
    at renderer (/Users/skalluri1/Workspace/sraone/marko-widgets-lasso/node_modules/marko-widgets/lib/defineRenderer.js:157:28)
    at render (/Users/skalluri1/Workspace/sraone/marko-widgets-lasso/src/pages/index/template.marko.js:28:5)
    at Object.render (/Users/skalluri1/Workspace/sraone/marko-widgets-lasso/node_modules/marko/runtime/marko-runtime.js:192:9)
    at Object.module.exports [as handler] (/Users/skalluri1/Workspace/sraone/marko-widgets-lasso/src/pages/index/index.js:6:14)
    at /Users/skalluri1/Workspace/sraone/marko-widgets-lasso/server.js:26:15
    at Layer.handle [as handle_request] (/Users/skalluri1/Workspace/sraone/marko-widgets-lasso/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/skalluri1/Workspace/sraone/marko-widgets-lasso/node_modules/express/lib/router/route.js:137:13)
```

**Comment by sraone** [comment]
@ianmcburnie yes, its kind of block because I can't have `w-id` for any child components.
