### ISSUE TITLE
ebay-tab: adding fake=true results in an error when no ebay-tab-panel present

### ISSUE THREAD

**Issue by BhavinPatel04** [eBay/ebayui-core#951]
# Bug Report

## Description
`<ebay-tab fake=true>...</ebay-tab>` 

Using the fake attr results in the below error:
````
Exception: TypeError: Cannot read property 'class' of undefined
    at render (/node_modules/@ebay/ebayui-core/dist/components/ebay-tab/template.marko.js:76:27)
    at Template.renderer (/node_modules/marko/src/runtime/components/legacy/renderer-legacy.js:172:9)
    at Template.hotReloadProxy (/node_modules/marko/src/hot-reload.js:101:31)
    at renderer (/node_modules/marko/src/runtime/components/legacy/defineRenderer-legacy.js:176:22)
    at wrappedRenderer (/node_modules/marko/src/runtime/helpers.js:285:13)
    at render (/src/fe-components/m-page-tabs/index.marko.js:30:3)
    at Template.renderer (/node_modules/marko/src/runtime/components/renderer.js:227:9)
    at hotReloadProxy (/node_modules/marko/src/hot-reload.js:101:31)
    at wrappedRenderer (/node_modules/marko/src/runtime/helpers.js:285:13)
    at render (/src/fe-components/m-top-nav/index.marko.js:58:5)
    at Template.renderer (/node_modules/marko/src/runtime/components/renderer.js:227:9)
    at hotReloadProxy (/node_modules/marko/src/hot-reload.js:101:31)
    at wrappedRenderer (/node_modules/marko/src/runtime/helpers.js:285:13)
    at renderBody (/src/pages/watchlist/large.marko.js:85:17)
    at safeRenderBody (/node_modules/marko/src/core-tags/core/await/renderer.js:8:9)
    at renderBody (/node_modules/marko/src/core-tags/core/await/renderer.js:187:37)
    at AsyncStream.error (/node_modules/marko/src/runtime/html/AsyncStream.js:442:13)
    at renderBody (/node_modules/marko/src/core-tags/core/await/renderer.js:183:26)
    at renderBody (/node_modules/marko/src/core-tags/core/await/renderer.js:194:28)
    at notifyCallbacks (/node_modules/marko/src/core-tags/core/await/AsyncValue.js:37:13)
    at AsyncValue.___resolve (/node_modules/marko/src/core-tags/core/await/AsyncValue.js:115:13)
````

## Workaround
Add empty `<ebay-tab-panel></ebay-tab-panel>`

**Comment by agliga** [comment]
The issue that is happening is the `<ebay-tab>` component breaks because there is no `<ebay-tab-panel>`. It seems that it requires at least 1 panel in order to render. 
Now a workaround for this would be to include a `<ebay-tab-panel>` (an empty tab panel works too). The  tab panel should be the content you are currently viewing on the page.

**Comment by ianmcburnie** [comment]
Thanks Andrew. The tab-panel is needed in order to get the correct skin markup, which creates the correct padding for the content. I can see how an app might want to only render the fake tabs though, and handle the content themselves. Sounds like a feature request.

**Comment by BhavinPatel04** [comment]
@agliga @ianmcburnie I confirm that the workaround to add empty `<ebay-tab-panel>` works. Will edit the issue.

**Comment by ianmcburnie** [comment]
Perhaps we split this into `ebay-tabs` and `ebay-fake-tabs` to avoid this pitfall.

**Comment by ianmcburnie** [comment]
Fixed in v6 branch. Closing.
